##### AWS CLOUD FOUNDATION - Ana Carolina Torres
Visualize with Application Composer
Description: Criar um Amazon EC2 simples
Resources:
  MinhaInstancia:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0es9277fb7eb570c9
      InstanceType: t2.micro
